---

- name: reload minio systemd
  systemd:
    name: minio
    daemon_reload: True
  tags:
    - install

- name: restart minio
  service:
    name: minio
    state: restarted
  tags:
    - install
